# Generated by Django 5.1.2 on 2024-10-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="dob",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="student",
            name="school",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
